
vim.keymap.set("n", "<leader><leader>", function() vim.cmd("so") end, { desc = "Source current file" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Scroll down (cursor centered)" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Scroll up (cursor centered)" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Next search result (centered)" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Prev search result (centered)" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Join lines (keep cursor)" })
vim.keymap.set("n", "<C-c>", ":nohl<CR>", { desc = "Clear search highlight" })
vim.keymap.set("n", "<leader>f", vim.lsp.buf.format, { desc = "Format file (LSP)" })
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = "Replace word under cursor globally" })
vim.keymap.set("n", "<leader>X", "<cmd>!chmod +x %<CR>", { desc = "Make file executable" })
vim.keymap.set("n", "<leader>d", [["_d]], { desc = "Delete to void register" })
vim.keymap.set("n", "x", '"_x', { desc = "Delete char (no register)" })
vim.keymap.set("n", "<leader>fp", function() vim.fn.setreg("+", vim.fn.expand("%:~")) end, { desc = "Copy file path to clipboard" })
vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle, { desc = "Toggle undotree" })
vim.keymap.set("n", "<leader>re", "<cmd>restart<cr>", { desc = "Restart Neovim" })
vim.keymap.set("n", "<leader>lr", function() vim.cmd("lsp restart") end, { desc = "Restart LSP" })

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move selection down" })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move selection up" })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left (stay in visual)" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right (stay in visual)" })
vim.keymap.set("x", "p", [["_dP]], { desc = "Paste over selection (keep yank)" })

vim.keymap.set("n", "<leader>sv", "<C-w>v", { desc = "Split window vertically" })
vim.keymap.set("n", "<leader>sh", "<C-w>s", { desc = "Split window horizontally" })
vim.keymap.set("n", "<leader>se", "<C-w>=", { desc = "Make splits equal size" })
vim.keymap.set("n", "<leader>sx", "<cmd>close<CR>", { desc = "Close current split" })

vim.keymap.set("n", "<leader>to", "<cmd>tabnew<CR>", { desc = "Open new tab" })
vim.keymap.set("n", "<leader>tx", "<cmd>tabclose<CR>", { desc = "Close current tab" })
vim.keymap.set("n", "<leader>tn", "<cmd>tabn<CR>", { desc = "Go to next tab" })
vim.keymap.set("n", "<leader>tp", "<cmd>tabp<CR>", { desc = "Go to previous tab" })
vim.keymap.set("n", "<leader>tf", "<cmd>tabnew %<CR>", { desc = "Open current file in new tab" })

vim.keymap.set("n", "gR", "<cmd>Telescope lsp_references<CR>", { desc = "LSP references" })
vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "gd", "<cmd>Telescope lsp_definitions<CR>", { desc = "LSP definitions" })
vim.keymap.set("n", "gi", "<cmd>Telescope lsp_implementations<CR>", { desc = "LSP implementations" })
vim.keymap.set("n", "gt", "<cmd>Telescope lsp_type_definitions<CR>", { desc = "LSP type definitions" })
vim.keymap.set("n", "<leader>vca", vim.lsp.buf.code_action, { desc = "Code actions" })
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Smart rename" })
vim.keymap.set("n", "<leader>D", function() require("snacks").picker.diagnostics_buffer() end, { desc = "Buffer diagnostics" })
vim.keymap.set("n", "df", vim.diagnostic.open_float, { desc = "Line diagnostics float" })
vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover documentation" })
vim.keymap.set("n", "<leader>lx", function() vim.diagnostic.config({ virtual_text = not vim.diagnostic.config().virtual_text }) end, { desc = "Toggle LSP virtual text" })

vim.keymap.set("n", "<leader>a", function() require("harpoon"):list():add() end, { desc = "Harpoon: add file" })
vim.keymap.set("n", "<C-e>", function() require("harpoon").ui:toggle_quick_menu(require("harpoon"):list()) end, { desc = "Harpoon: toggle menu" })
vim.keymap.set("n", "<C-y>", function() require("harpoon"):list():select(1) end, { desc = "Harpoon: jump to file 1" })
vim.keymap.set("n", "<C-i>", function() require("harpoon"):list():select(2) end, { desc = "Harpoon: jump to file 2" })
vim.keymap.set("n", "<C-n>", function() require("harpoon"):list():select(3) end, { desc = "Harpoon: jump to file 3" })
vim.keymap.set("n", "<C-s>", function() require("harpoon"):list():select(4) end, { desc = "Harpoon: jump to file 4" })
vim.keymap.set("n", "<C-S-P>", function() require("harpoon"):list():prev() end, { desc = "Harpoon: prev file" })
vim.keymap.set("n", "<C-S-N>", function() require("harpoon"):list():next() end, { desc = "Harpoon: next file" })

vim.keymap.set("n", "<leader>pr", "<cmd>Telescope oldfiles<CR>", { desc = "Recent files" })
vim.keymap.set("n", "<leader>pWs", function() require("telescope.builtin").grep_string({ search = vim.fn.expand("<cWORD>") }) end, { desc = "Grep WORD under cursor" })
vim.keymap.set("n", "<leader>ths", "<cmd>Telescope themes<CR>", { desc = "Theme switcher" })

vim.keymap.set("n", "<leader>pws", function() require("snacks").picker.grep_word() end, { desc = "Grep word / selection" })
vim.keymap.set("n", "<leader>pk", function() require("snacks").picker.keymaps() end, { desc = "Search keymaps" })
vim.keymap.set("n", "<leader>vh", function() require("snacks").picker.help() end, { desc = "Help pages" })
vim.keymap.set("n", "<leader>th", function() require("snacks").picker.colorschemes() end, { desc = "Pick colorscheme" })
vim.keymap.set("n", "<leader>pt", function() require("snacks").picker.todo_comments() end, { desc = "Todo comments (all)" })
vim.keymap.set("n", "<leader>pT", function() require("snacks").picker.todo_comments({ keywords = { "TODO","FIXME" } }) end, { desc = "Todo comments (main)" })

vim.keymap.set("n", "<leader>lg", function() require("snacks").lazygit() end, { desc = "Open Lazygit" })
vim.keymap.set("n", "<leader>gl", function() require("snacks").lazygit.log() end, { desc = "Lazygit logs" })
vim.keymap.set("n", "<leader>rN", function() require("snacks").rename.rename_file() end, { desc = "Rename current file" })
vim.keymap.set("n", "<leader>dB", function() require("snacks").bufdelete() end, { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>gbr", function() require("snacks").picker.git_branches() end, { desc = "Git branches picker" })

vim.keymap.set("n", "]h", function() require("gitsigns").next_hunk() end, { desc = "Next git hunk" })
vim.keymap.set("n", "[h", function() require("gitsigns").prev_hunk() end, { desc = "Prev git hunk" })
vim.keymap.set("n", "<leader>gs", function() require("gitsigns").stage_hunk() end, { desc = "Stage hunk" })
vim.keymap.set("n", "<leader>gr", function() require("gitsigns").reset_hunk() end, { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>gS", function() require("gitsigns").stage_buffer() end, { desc = "Stage buffer" })
vim.keymap.set("n", "<leader>gR", function() require("gitsigns").reset_buffer() end, { desc = "Reset buffer" })
vim.keymap.set("n", "<leader>gu", function() require("gitsigns").undo_stage_hunk() end, { desc = "Undo stage hunk" })
vim.keymap.set("n", "<leader>gp", function() require("gitsigns").preview_hunk() end, { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>gbl", function() require("gitsigns").blame_line({ full = true }) end, { desc = "Blame line (full)" })
vim.keymap.set("n", "<leader>gB", function() require("gitsigns").toggle_current_line_blame() end, { desc = "Toggle line blame" })
vim.keymap.set("n", "<leader>gd", function() require("gitsigns").diffthis() end, { desc = "Diff this" })
vim.keymap.set("n", "<leader>gD", function() require("gitsigns").diffthis("~") end, { desc = "Diff this ~" })
vim.keymap.set("n", "<leader>gg", "<cmd>tabnew | Git | only<cr>", { desc = "Fugitive (fullscreen)" })

vim.keymap.set("n", "<leader>wl", function() require("telescope").extensions.git_worktree.git_worktrees() end, { desc = "List git worktrees" })
vim.keymap.set("n", "<leader>wc", function() require("telescope").extensions.git_worktree.create_git_worktree() end, { desc = "Create git worktree" })

vim.keymap.set("n", "<leader>xw", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Workspace diagnostics" })
vim.keymap.set("n", "<leader>xd", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Document diagnostics" })
vim.keymap.set("n", "<leader>xq", "<cmd>Trouble quickfix toggle<CR>", { desc = "Quickfix list" })
vim.keymap.set("n", "<leader>xl", "<cmd>Trouble loclist toggle<CR>", { desc = "Location list" })
vim.keymap.set("n", "<leader>xt", "<cmd>Trouble todo toggle<CR>", { desc = "Todos in Trouble" })

vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory (Oil)" })
vim.keymap.set("n", "<leader>-", function() require("oil").toggle_float() end, { desc = "Oil float window" })

vim.keymap.set("n", "<leader>tt", nil, { desc = "Toggle float terminal" })
vim.keymap.set("n", "<C-_>", nil, { desc = "Toggle terminal (Ctrl-/)" })
vim.keymap.set("n", "<leader>tH", nil, { desc = "Toggle horizontal terminal" })
vim.keymap.set("n", "<leader>tn", nil, { desc = "Node REPL terminal" })
