INSERT INTO keymaps (user_id, source_id, key_sequence, mode, description, category, difficulty, is_builtin) VALUES
-- Beginner motions
(NULL, NULL, 'h',       'n', 'Move left one character',                'motion',    'beginner',     TRUE),
(NULL, NULL, 'j',       'n', 'Move down one line',                     'motion',    'beginner',     TRUE),
(NULL, NULL, 'k',       'n', 'Move up one line',                       'motion',    'beginner',     TRUE),
(NULL, NULL, 'l',       'n', 'Move right one character',               'motion',    'beginner',     TRUE),
(NULL, NULL, 'w',       'n', 'Move forward to next word start',        'motion',    'beginner',     TRUE),
(NULL, NULL, 'b',       'n', 'Move backward to previous word start',   'motion',    'beginner',     TRUE),
(NULL, NULL, 'e',       'n', 'Move forward to end of word',            'motion',    'beginner',     TRUE),
(NULL, NULL, '0',       'n', 'Move to beginning of line',              'motion',    'beginner',     TRUE),
(NULL, NULL, '$',       'n', 'Move to end of line',                    'motion',    'beginner',     TRUE),
(NULL, NULL, 'gg',      'n', 'Move to first line of file',             'motion',    'beginner',     TRUE),
(NULL, NULL, 'G',       'n', 'Move to last line of file',              'motion',    'beginner',     TRUE),
-- Beginner editing
(NULL, NULL, 'i',       'n', 'Enter insert mode before cursor',        'editing',   'beginner',     TRUE),
(NULL, NULL, 'a',       'n', 'Enter insert mode after cursor',         'editing',   'beginner',     TRUE),
(NULL, NULL, 'o',       'n', 'Open new line below and enter insert mode', 'editing', 'beginner',    TRUE),
(NULL, NULL, 'O',       'n', 'Open new line above and enter insert mode', 'editing', 'beginner',    TRUE),
(NULL, NULL, 'x',       'n', 'Delete character under cursor',          'editing',   'beginner',     TRUE),
(NULL, NULL, 'dd',      'n', 'Delete current line',                    'editing',   'beginner',     TRUE),
(NULL, NULL, 'yy',      'n', 'Yank (copy) current line',               'editing',   'beginner',     TRUE),
(NULL, NULL, 'p',       'n', 'Paste after cursor',                     'editing',   'beginner',     TRUE),
(NULL, NULL, 'P',       'n', 'Paste before cursor',                    'editing',   'beginner',     TRUE),
(NULL, NULL, 'u',       'n', 'Undo last change',                       'editing',   'beginner',     TRUE),
(NULL, NULL, '<C-r>',   'n', 'Redo last undone change',                'editing',   'beginner',     TRUE),
-- Beginner navigation
(NULL, NULL, '/',       'n', 'Search forward',                         'navigation','beginner',     TRUE),
(NULL, NULL, 'n',       'n', 'Next search result',                     'navigation','beginner',     TRUE),
(NULL, NULL, 'N',       'n', 'Previous search result',                 'navigation','beginner',     TRUE),
(NULL, NULL, 'ZZ',      'n', 'Save and quit',                          'navigation','beginner',     TRUE),
(NULL, NULL, ':w',      'n', 'Save file',                              'navigation','beginner',     TRUE),
(NULL, NULL, ':q',      'n', 'Quit',                                   'navigation','beginner',     TRUE),
(NULL, NULL, ':wq',     'n', 'Save and quit',                          'navigation','beginner',     TRUE),
-- Intermediate editing
(NULL, NULL, 'ciw',     'n', 'Change inner word',                      'editing',   'intermediate', TRUE),
(NULL, NULL, 'daw',     'n', 'Delete around word',                     'editing',   'intermediate', TRUE),
(NULL, NULL, 'yiw',     'n', 'Yank inner word',                        'editing',   'intermediate', TRUE),
(NULL, NULL, 'cw',      'n', 'Change to end of word',                  'editing',   'intermediate', TRUE),
(NULL, NULL, 'D',       'n', 'Delete to end of line',                  'editing',   'intermediate', TRUE),
(NULL, NULL, 'C',       'n', 'Change to end of line',                  'editing',   'intermediate', TRUE),
(NULL, NULL, 'J',       'n', 'Join current line with next',            'editing',   'intermediate', TRUE),
(NULL, NULL, '.',       'n', 'Repeat last change',                     'editing',   'intermediate', TRUE),
(NULL, NULL, 'A',       'n', 'Append at end of line',                  'editing',   'intermediate', TRUE),
(NULL, NULL, 'I',       'n', 'Insert at beginning of line',            'editing',   'intermediate', TRUE),
(NULL, NULL, 's',       'n', 'Substitute character (delete and enter insert)', 'editing', 'intermediate', TRUE),
(NULL, NULL, 'S',       'n', 'Substitute line (delete line and enter insert)', 'editing', 'intermediate', TRUE),
-- Intermediate motion
(NULL, NULL, '*',       'n', 'Search for word under cursor (forward)', 'motion',    'intermediate', TRUE),
(NULL, NULL, '#',       'n', 'Search for word under cursor (backward)','motion',    'intermediate', TRUE),
(NULL, NULL, '%',       'n', 'Jump to matching bracket or paren',      'motion',    'intermediate', TRUE),
(NULL, NULL, 'f{char}', 'n', 'Find next char on line',                 'motion',    'intermediate', TRUE),
(NULL, NULL, 't{char}', 'n', 'Move before next char on line',          'motion',    'intermediate', TRUE),
(NULL, NULL, '<C-d>',   'n', 'Scroll down half page',                  'motion',    'intermediate', TRUE),
(NULL, NULL, '<C-u>',   'n', 'Scroll up half page',                    'motion',    'intermediate', TRUE),
(NULL, NULL, '<C-f>',   'n', 'Scroll forward full page',               'motion',    'intermediate', TRUE),
(NULL, NULL, '<C-b>',   'n', 'Scroll backward full page',              'motion',    'intermediate', TRUE),
(NULL, NULL, 'zz',      'n', 'Center current line in window',          'motion',    'intermediate', TRUE),
(NULL, NULL, 'zt',      'n', 'Move current line to top of window',     'motion',    'intermediate', TRUE),
(NULL, NULL, 'zb',      'n', 'Move current line to bottom of window',  'motion',    'intermediate', TRUE),
-- Intermediate navigation
(NULL, NULL, 'gt',      'n', 'Go to next tab',                         'navigation','intermediate', TRUE),
(NULL, NULL, 'gT',      'n', 'Go to previous tab',                     'navigation','intermediate', TRUE),
-- Advanced editing
(NULL, NULL, 'q{a}',    'n', 'Record macro into register',             'editing',   'advanced',     TRUE),
(NULL, NULL, '@{a}',    'n', 'Play macro from register',               'editing',   'advanced',     TRUE),
(NULL, NULL, '@@',      'n', 'Repeat last macro',                      'editing',   'advanced',     TRUE),
(NULL, NULL, 'ca"',     'n', 'Change around double quotes',            'editing',   'advanced',     TRUE),
(NULL, NULL, 'di(',     'n', 'Delete inside parentheses',              'editing',   'advanced',     TRUE),
(NULL, NULL, 'ci[',     'n', 'Change inside square brackets',          'editing',   'advanced',     TRUE),
(NULL, NULL, 'da{',     'n', 'Delete around curly braces',             'editing',   'advanced',     TRUE),
(NULL, NULL, 'gv',      'n', 'Reselect last visual selection',         'editing',   'advanced',     TRUE),
-- Advanced motion
(NULL, NULL, 'm{a}',    'n', 'Set mark at cursor position',            'motion',    'advanced',     TRUE),
(NULL, NULL, '''{a}',   'n', 'Jump to marked position',                'motion',    'advanced',     TRUE),
(NULL, NULL, '<C-o>',   'n', 'Jump to previous location in jumplist',  'motion',    'advanced',     TRUE),
(NULL, NULL, '<C-i>',   'n', 'Jump to next location in jumplist',      'motion',    'advanced',     TRUE),
-- Advanced lsp
(NULL, NULL, 'gd',      'n', 'Go to definition (native LSP)',          'lsp',       'advanced',     TRUE),
(NULL, NULL, 'K',       'n', 'Show documentation (native LSP)',        'lsp',       'advanced',     TRUE),
-- Visual mode
(NULL, NULL, 'V',       'v', 'Select current line in visual mode',     'editing',   'intermediate', TRUE),
-- Visual block
(NULL, NULL, '<C-v>',   'n', 'Enter visual block mode',                'editing',   'intermediate', TRUE)
ON CONFLICT DO NOTHING;
